### ISSUE TITLE
bug in local installation

### ISSUE THREAD

**Issue by rabernat** [guidov/pygamman#1]
I am trying to run this code on a shared cluster ([yellowstone](https://www2.cisl.ucar.edu/resources/yellowstone)), where I can't do a global installation. I did a local install instead using [the user scheme](https://docs.python.org/2/install/#alternate-installation-the-user-scheme):

```
$ python setup.py install --user
```

This went well, and I can import the module. However, when I try to actually run the example, I get an error:

```
$ python neutral_density_test.py 
0.000127370614791
24.0
[ 35.066  35.086  35.089  35.078  35.025  34.851  34.696  34.572  34.531
  34.509  34.496  34.452  34.458  34.456  34.488  34.536  34.579  34.612
  34.642  34.657  34.685  34.707  34.72   34.729]
[ 12.25   12.21   12.09   11.99   11.69   10.54    9.35    8.36    7.86
   7.43    6.87    6.04    5.5     4.9     4.04    3.29    2.78    2.45
   2.211   2.011   1.894   1.788   1.554   1.38 ]
[  1.00000000e+00   4.80000000e+01   9.70000000e+01   1.45000000e+02
   1.94000000e+02   2.91000000e+02   3.88000000e+02   4.85000000e+02
   5.81000000e+02   6.78000000e+02   7.75000000e+02   8.72000000e+02
   9.69000000e+02   1.06600000e+03   1.26000000e+03   1.45400000e+03
   1.64700000e+03   1.84100000e+03   2.02000000e+03   2.21600000e+03
   2.41300000e+03   2.61100000e+03   2.87800000e+03   3.00000000e+03]
187.317
-41.6667
24
At line 2374 of file pygamman/fortran/gamman.f (unit = 20, file = '')
Fortran runtime error: File '/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/site-packages/pygamman/ocndata/llp.fdt' does not exist
```

It looks like it is not looking for the data file in the right place.

Any ideas on how to overcome this?

**Comment by rabernat** [comment]
Just to follow up, I was able to hack around this problem by editing setup.py and replacing _ocndataprefix_ with the path to the installed data file (in my case, ~/.local/lib/python2.7/site-packages/pygamman/ocndata). I couldn't figure out a more robust solution.

**Comment by guidov** [comment]
You could probably also modify the fortran code directly if necessary. Glad
you figured out a solution.
Sorry the code is so clunky , I just wanted to get something working
quickly.
I hope you find this python wrapper useful and please let me know if you
find any problems.

**Comment by rabernat** [comment]
I find it extremely useful! Thanks for your reply!
