### ISSUE TITLE
gamma_n only works for single profiles?

### ISSUE THREAD

**Issue by jessecusack** [guidov/pygamman#3]
Thanks for making this, it took me a little while but I got it installed in the end (after reading the other closed issues)! I get the following error when using arrays (section of profiles):

`error: failed in converting 1st argument 's' of gamman.gamma_n to C/Fortran array`

Presumably the function can only handle single profiles at a time?

**Comment by guidov** [comment]
Hi Jesse,

Try this:

import numpy as np
from netCDF4 import Dataset
from pygamman import gamman as gn

# load some WOCE data:

# https://dl.dropboxusercontent.com/u/4004641/wghc_params.nc

# https://dl.dropboxusercontent.com/u/4004641/woce_basin_mask.nc

wghcf = Dataset("wghc_params.nc", 'r')
wmask = Dataset("woce_basin_mask.nc", 'r')

wdepth = wghcf.variables['ZAX'][:]
wlon = wghcf.variables['LON'][:]
wlat = wghcf.variables['LAT'][:]
wpres = wghcf.variables['PRES'][:]
wtemp = wghcf.variables['TEMP'][:,:,:]
wpottemp = wghcf.variables['TPOTEN'][:,:,:]
wsalt = wghcf.variables['SALINITY'][:,:,:]
wsig0 = wghcf.variables['SIG0'][:,:,:]
wsig2 = wghcf.variables['SIG2'][:,:,:]
wsig4 = wghcf.variables['SIG4'][:,:,:]
wgamman = wghcf.variables['GAMMAN'][:,:,:]
wo2 = wghcf.variables['OXYGEN'][:,:,:]
wso2 = wghcf.variables['SILICATE'][:,:,:]
wno2 = wghcf.variables['NITRATE'][:,:,:]
wpo4 = wghcf.variables['PHOSPH'][:,:,:]

def gamman3d(arrsalt,arrtemp,arrpres,arrlon,arrlat,lonp=0,latp=0):
    #get dim sizes
    # lonp and latp are offsets to start at
    zlen=arrsalt.shape[0]
    ylen=arrsalt.shape[1]
    xlen=arrsalt.shape[2]
    # create blank masked array to hold gamma_n
    g3d=np.ma.zeros((zlen,ylen,xlen),dtype=float)
    el3d=np.ma.zeros((zlen,ylen,xlen),dtype=float)
    eh3d=np.ma.zeros((zlen,ylen,xlen),dtype=float)
    # set all the grid to missing value
    g3d.fill(-99.1)
    el3d.fill(-99.1)
    eh3d.fill(-99.1)
    # loop over depth profiles at each lat and lon to create a gamma_n
profile and fill 3-D array
    # latitudes are restricted to >= 80S and <= 64N
    for i in range(0,ylen):
        ix=i+latp
        if arrlat[ix] >=-80.0 and arrlat[ix] <=64.0:
            for j in range(0,xlen):
                jx=j+lonp
                g3d[:,i,j],el3d[:,i,j],eh3d[:,i,j]=
gn.gamma_n(arrsalt[:,i,j],arrtemp[:,i,j], \

 arrpres[:,i,j],zlen,arrlon[jx],arrlat[ix])
    # Mask out missing values and return
    g3dmask=np.ma.masked_where(g3d <= -99.0, g3d)
    el3dmask=np.ma.masked_where(el3d <= -99.0, el3d)
    eh3dmask=np.ma.masked_where(eh3d <= -99.0, eh3d)
    return g3dmask,el3dmask,eh3dmask

# zonal average woce variable

def wzonavg(wocevar):
    zvar=np.ma.average(wocevar,axis=2)
    return zvar

zwgamman=wzonavg(wgamman)

# can reproduce figure 2 of Ferrari et al 2014 (PNAS) with zwgamman

g3darr,el3darr,eh3darr = gamman3d(wsalt,wtemp,wpres,wlon,wlat)

zg3darr = wzonavg(g3darr)

# zwgamman should == zg3darr

# can reproduce figure 2 of Ferrari et al 2014 (PNAS) with zg3darr

---

**Comment by jessecusack** [comment]
Ok great, I see you loop over each profile. Thanks for the WOCE relevant code, might come in handy.
